default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogs_development

test:
  <<: *default
  database: blogs_test

production:
  <<: *default
  database: <%= ENV["PROD_DB_NAME"] %>
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
  host: <%= ENV["PROD_DB_HOST"] %>
  port: <%= ENV["PROD_DB_PORT"] %>
